name: railyard
recipe: pantheon
config:
  disableAutoComposerInstall: true
  env: dev
  framework: wordpress
  webroot: web
  xdebug: true
services:
  appserver:
    build:
      - |
        if [ -n "$GITHUB_TOKEN" ] ; then
          cd $LANDO_MOUNT && composer config --global --auth --unset github-oauth.github.com && composer config --global github-oauth.github.com $GITHUB_TOKEN
        fi
      - |
        if [ -n "$TERMINUS_TOKEN" ] ; then
          cd $LANDO_MOUNT && terminus auth:login --machine-token=$TERMINUS_TOKEN
        fi
      - |
        if [ -n "$PACKAGIST_TOKEN" ] && [ -n "$PACKAGIST_USER" ] ; then
          cd $LANDO_MOUNT && composer config --global --auth http-basic.repo.packagist.com $PACKAGIST_USER $PACKAGIST_TOKEN
        fi
      - mkdir -p ~/.terminus/plugins
      - composer config --global process-timeout 2000
      - |
        if [ ! -d ~/.terminus/plugins/terminus-build-tools-plugin ] ; then
          composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:2.0.0-alpha4
        fi
        if [ ! -d ~/.terminus/plugins/terminus-secrets-plugin ] ; then
          composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1
        fi
      - cd $LANDO_MOUNT && composer build-assets-dev
  database:
    portforward: 3307
proxy:
  edge:
    - railyard.lndo.site
tooling:
  sniff:
    service: appserver
    cmd:
      - composer
      - code-sniff
  test:
    service: appserver
    cmd:
      - composer
      - unit-test